server:
  port: 8082
spring:
  application:
    name: ticket-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/highwayTicketManagementSystemTicketService?createDatabaseIfNotExist=true
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 0